#cloud-config
package_update: true
package_upgrade: true

users:
  - defualt:
  - name: langchain
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    passwd: "$6$rounds=4096$gKMmPH6zFbXXCKzP$nrDOVDBwGzUtRQLq4cEnEcmW.B3MpWiDZ0x0lm2LZfNcYfA2IQUzIMvPZyzYypO7pIptxtOZrMOzR3yqMSB4v/"  # LangChain123!
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEWRUU6TrJRByHIBE5umRvGGM1IFZcMx+lLO4LtHYwiZ Zay@Zay-Legend-OS.local

packages:
  - python3
  - python3-pip
  - python3-venv
  - nginx
  - ufw
  - git

runcmd:
  - ufw allow OpenSSH
  - ufw allow 80
  - ufw allow 443
  - ufw allow 5000
  - ufw --force enable

  - passwd -l root
  - sed -i 's/^PermitRootLogin yes/PermitRootLogin no/' /etc/ssh/sshd_config
  - systemctl restart sshd

  - mkdir -p /home/langchain/langchain-app
  - chown langchain:langchain /home/langchain/langchain-app
  - python3 -m venv /home/langchain/langchain-app/venv
  - /home/langchain/langchain-app/venv/bin/pip install --upgrade pip
  - /home/langchain/langchain-app/venv/bin/pip install flask gunicorn python-dotenv

  - echo "from flask import Flask, jsonify\napp = Flask(__name__)\n@app.route('/')\ndef index():\n    return jsonify({'status': 'LangChain API is alive!'})" > /home/langchain/langchain-app/api.py
  - chown langchain:langchain /home/langchain/langchain-app/api.py

  - |
    echo "[Unit]
    Description=Gunicorn LangChain API
    After=network.target

    [Service]
    User=langchain
    Group=langchain
    WorkingDirectory=/home/langchain/langchain-app
    Environment=PATH=/home/langchain/langchain-app/venv/bin
    ExecStart=/home/langchain/langchain-app/venv/bin/gunicorn --bind 0.0.0.0:5000 api:app

    [Install]
    WantedBy=multi-user.target" > /etc/systemd/system/langchain-api.service

  - systemctl daemon-reload
  - systemctl enable langchain-api
  - systemctl start langchain-api

final_message: "✅ Setup complete! Login as 'langchain' (LangChain123!) or via SSH key 🚀"
